
package com.view;

// Generated Jul 12, 2016 2:16:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * Serv generated by hbm2java
 */
public class Serv implements java.io.Serializable {

	private Integer id;
	private String name;
	private String strength;

	public Serv() {
	}

	public Serv(String name, String strength) {
		this.name = name;
		this.strength = strength;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStrength() {
		return this.strength;
	}

	public void setStrength(String strength) {
		this.strength = strength;
	}

}
